apiVersion: v1
kind: Service
metadata:
  name: devops-capstone
spec:
  selector:
    app: devops-capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone
spec:
  selector:
    matchLabels:
      app: devops-capstone
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-capstone
    spec:
      containers:
      - name: devops-capstone
        image: minhtri188/devops-capstone
        ports:
        - containerPort: 80
